### ISSUE TITLE
アプリケーションの雛形作成

### ISSUE THREAD

**Issue by ojfubd** [ojfubd/storyshare#5]
- [x]全体のデザイン作成
- [ x]ビュー
- [x ]マイページ
- [ x]トップページ
- [ x]設定ページ
- [ x]データ完了
- [x] ユーザー

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。

GitHubProjectsが確認できませんでしたので、こちらご確認いただいてもよろしいですか？
(作成してあるが見れない場合、private設定にしてあることが多いです。)
よろしくお願いします。
